baseURL: "https://cfy.cz/"
title: "CFY.cz"

enableRobotsTXT: true

theme: "compose"

enableGitInfo: true

languageCode: en-us
defaultContentLanguage: en

#disableKinds:
#  - "taxonomy"
#  - "taxonomyTerm"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"