baseURL: "https://cfy.cz/"
title: "CFY.cz"
enableRobotsTXT: true
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
theme: "compose"
enableGitInfo: true

# disableKinds = ["taxonomy", "taxonomyTerm"]

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"