#  menu items
[[main]]
  name = "Blog"
  weight = 5
  url = "blog/"

[[main]]
  name = "Dokumentace"
  weight = 2
  url = "docs/"

[[main]]
  name = "Návody"
  weight = 2
  url = "tutorials/"

#[[main]]
#  name = "Example"
#  weight = 3
#  url = "https://docs.neuralvibes.com"

# [[main]]
#   name = "Blog"
#   weight = 4
#   url = "blog/"
